// <auto-generated />
using System;
using MaxEndLabs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaxEndLabs.Data.Migrations
{
    [DbContext(typeof(MaxEndLabsDbContext))]
    [Migration("20260315161849_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaxEndLabs.Data.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("CartId", "ProductId", "ProductVariantId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Upper Body",
                            Slug = "upper-body"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lower Body",
                            Slug = "lower-body"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoes",
                            Slug = "shoes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Supplements",
                            Slug = "supplements"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Accessories",
                            Slug = "accessories"
                        });
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("MainImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "The three words that motivated generations of weightlifters are back! As worn by Bulgaria’s -85kg snatch record holder from the ‘90s, Georgi Gardev. Oversized fit.",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/WBN1.jpg",
                            Name = "Why Be Normal T-shirt",
                            Price = 40m,
                            Slug = "why-be-normal-tshirt",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "The official t-shirt of Olympic Champion Karlos Nasar. Made in collaboration with the greatest weightlifter of a generation, the Nasar ‘I Win, You Lose’ T-shirt.",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/6_155b8e55-8336-438c-a966-fdec261cd0cb.jpg",
                            Name = "Nasar I Win, You Lose T-shirt",
                            Price = 45m,
                            Slug = "nasar-i-win-you-lose-tshirt",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "Celebrate the record-breaking power of Olympic Champion Karlos Nasar with this exclusive t-shirt. Featuring the iconic ‘404’ — marking the world and Olympic total record.",
                            IsPublished = true,
                            MainImageUrl = "https://karlosnasar.com/storage/products/371146981.jpg",
                            Name = "T-shirt 404",
                            Price = 30m,
                            Slug = "tshirt-404",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "The official t-shirt of Olympic Champion Karlos Nasar. Made in collaboration with the greatest weightlifter of a generation, the Nasar ‘I Win, You Lose’ Shorts",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/18_75ea3d05-1e8b-4fbc-af35-a41fb16930b3.jpg",
                            Name = "Nasar I Win, You Lose Shorts",
                            Price = 62.95m,
                            Slug = "nasar-i-win-you-lose-shorts",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "The official t-shirt of Olympic Champion Karlos Nasar. Made in collaboration with the greatest weightlifter of a generation, the Nasar ‘I Win, You Lose’ Leggings",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/13_2144736c-1165-42a7-87f7-c90db6a3c274.jpg",
                            Name = "Nasar I Win, You Lose Leggings",
                            Price = 70m,
                            Slug = "nasar-i-win-you-lose-leggings",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "When Karlos Nasar shattered the world record, he did it in LUXIAOJUN lifters. That moment wasn’t just victory. It was domination. To celebrate his legacy and mindset, we present the Karlos Edition: built for lifters who don't just compete, they take over.",
                            IsPublished = true,
                            MainImageUrl = "https://luxiaojun.com/cdn/shop/files/LUXIAOJUN_PowerPro_Weightlifting_Shoes_Karlos_Edition_Pair.jpg",
                            Name = "LUXIAOJUN PowerPro Weightlifting Shoes (Karlos)",
                            Price = 195m,
                            Slug = "luxiaojun-powerpro-weightlifting-shoes-karlos",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "Fuel your performance with Gold Standard 100% Whey — a premium protein powder built for muscle support and post-workout recovery. Featuring 24g of protein and 5.5g of BCAAs per serving, with whey protein isolate as the No. 1 ingredient.",
                            IsPublished = true,
                            MainImageUrl = "https://www.optimumnutrition.com/cdn/shop/files/on-1101490_Image_01.jpg",
                            Name = "GOLD STANDARD 100% WHEY",
                            Price = 99.99m,
                            Slug = "gold-standard-100-whey",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "Boost your performance with Micronized Creatine Powder — designed to support muscle strength and power, explosive movements, and ATP recycling. Delivering 5g of creatine monohydrate per serving and stackable with Gold Standard 100% Whey for complete muscle support.",
                            IsPublished = true,
                            MainImageUrl = "https://www.optimumnutrition.com/cdn/shop/files/on-1102271_Image_01.png",
                            Name = "Micronized Creatine Powder",
                            Price = 30m,
                            Slug = "micronized-creatine-powder",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedAt = new DateOnly(2026, 2, 10),
                            Description = "Designed by Olympic Champion Karlos Nasar to elevate your training. These classic quick-release straps offer performance and durability with Karlos’s signature branding.",
                            IsPublished = true,
                            MainImageUrl = "https://eustore.weightliftinghouse.com/cdn/shop/files/nasar_house_1.jpg",
                            Name = "Nasar House Straps",
                            Price = 26m,
                            Slug = "nasar-house-straps",
                            UpdatedAt = new DateOnly(2026, 2, 10)
                        });
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 1,
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 2,
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 2,
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 2,
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 2,
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 3,
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 3,
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 3,
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 3,
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 4,
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 4,
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 4,
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 4,
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 5,
                            VariantName = "Size S / Color: Black"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 5,
                            VariantName = "Size M / Color: Black"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 5,
                            VariantName = "Size L / Color: Black"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 5,
                            VariantName = "Size XL / Color: Black"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 6,
                            VariantName = "Size 38 EU"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 6,
                            VariantName = "Size 39 EU"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 6,
                            VariantName = "Size 40 EU"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 6,
                            VariantName = "Size 41 EU"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 6,
                            VariantName = "Size 42 EU"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 6,
                            VariantName = "Size 43 EU"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 6,
                            VariantName = "Size 44 EU"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 6,
                            VariantName = "Size 45 EU"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 6,
                            VariantName = "Size 46 EU"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 6,
                            VariantName = "Size 47 EU"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 6,
                            VariantName = "Size 48 EU"
                        },
                        new
                        {
                            Id = 32,
                            Price = 99.99m,
                            ProductId = 7,
                            VariantName = "Double Rich Chocolate / 2.26KG"
                        },
                        new
                        {
                            Id = 33,
                            Price = 30m,
                            ProductId = 8,
                            VariantName = "Unflavored / 317g"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 9,
                            VariantName = "Color: Black and Green"
                        });
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d333796b-4dd0-410c-92fd-481a6dc3fd0d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "e444796b-4dd0-410c-92fd-481a6dc3fd0d",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "06313180-fa45-42b5-ac33-1333f673455d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4bfdb153-a446-4968-a40f-34adc37a6f28",
                            Email = "admin@labs.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LABS.COM",
                            NormalizedUserName = "ADMIN@LABS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFn+JSWstBTrgdKXnCbFFlyXn3VHglaT/4nEmFCUnSexw+jwdpB9hbPnuyX2myzcXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c0142471-6ffd-44b4-b430-8b3c7acf8fbf",
                            TwoFactorEnabled = false,
                            UserName = "admin@labs.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "06313180-fa45-42b5-ac33-1333f673455d",
                            RoleId = "d333796b-4dd0-410c-92fd-481a6dc3fd0d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.CartItem", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaxEndLabs.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaxEndLabs.Data.Models.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Product", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ProductVariant", b =>
                {
                    b.HasOne("MaxEndLabs.Data.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ShoppingCart", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.Product", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ProductVariant", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MaxEndLabs.Data.Models.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
